version: "3"

services:
  app:
    env_file:
      - ./app/.env
    depends_on:
      - "api"

  api:
    env_file:
      - ./api/src/config/config.env
    ports:
      - "8080:8080"
    links:
      - mongo:mongo
    depends_on:
      - "mongo"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  mongo-seed:
    container_name: mongo-seed
    build:
      context: .
      dockerfile: seed/Dockerfile
    image: hypertube-mongo-seed
    links:
      - mongo:mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/hypertube
    depends_on:
      - "mongo"
