version: "3"

services:
  app:
    container_name: app-dev
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    image: hypertube-app
    volumes:
      - ./app:/app
      - /app/node_modules

  api:
    container_name: api-dev
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    image: hypertube-api
    volumes:
      - ./api:/api
      - /api/node_modules

  mongo:
    container_name: mongo-dev
    build:
      context: ./mongo
      dockerfile: Dockerfile
    image: hypertube-mongo
