version: "3"

services:
  app:
    container_name: app-prod
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    image: hypertube-app-prod
    environment:
      - NODE_ENV=production
    ports:
      - "3000:80"

  api:
    container_name: api-prod
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
    image: hypertube-api-prod

  mongo:
    container_name: mongo-prod
    build:
      context: ./mongo
      dockerfile: Dockerfile
    image: hypertube-mongo-prod
