version: "3"

services:
  app:
    container_name: app-prod
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    image: devessier/hypertube-app
    environment:
      - NODE_ENV=production
      - PORT=80
    ports:
      - "3000:80"

  api:
    container_name: api-prod
    build:
      context: ./api
      dockerfile: Dockerfile.prod
    environment:
      - NODE_ENV=production
    image: devessier/hypertube-api

  mongo:
    container_name: mongo-prod

  mongo-seed:
    image: devessier/hypertube-mongo-seed
