version: "3"

services:
  app:
    container_name: app
    build:
      context: ../.
      dockerfile: docker/app/Dockerfile.dev
    image: hypertube-app
    environment:
      - NODE_ENV=development
      - TZ=Europe/Paris
      - VUE_APP_BASE_URL=http://localhost:8080/v1
      - VUE_APP_I18N_LOCALE=en
      - VUE_APP_I18N_FALLBACK_LOCALE=en
    volumes:
      - ./../app:/usr/src/app
    ports:
      - "3000:3000"

  api:
    container_name: api
    build:
      context: ../.
      dockerfile: docker/api/Dockerfile.dev
    image: hypertube-api
    env_file:
      - ./api/api.env
    volumes:
      - ./../api:/usr/src/api
    ports:
      - "8080:8080"
    links:
      - mongo:mongo
    depends_on:
      - "mongo"

  mongo:
    container_name: mongo
    build:
      context: ../.
      dockerfile: docker/mongo/Dockerfile.dev
    image: hypertube-mongo
    volumes:
      - ./mongo/data/db:/data/db
    ports:
      - "27017:27017"
