FROM node:lts-alpine

RUN apk update && apk add ffmpeg && rm -rf /var/cache/apk/*

WORKDIR /api

COPY package.json .
COPY yarn.lock .

RUN yarn install --frozen-lockfile

COPY . .

EXPOSE 8080

CMD ["yarn", "start"]
